spring.application.name=Project_DATN_SD08_BaseBallCapSales
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DvtdHub1;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Duong03112007
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt.secret-key=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
jwt.time-life=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tienmnhat@gmail.com
spring.mail.password=iipu ttaf mlwz kcqw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.datatype.datetime.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh
#thanh toan onl
mbbank.bank-code=MB
mbbank.bank-name=MB Bank
mbbank.account-number=001292007
mbbank.account-name=NGUYEN HAI DANG
mbbank.vietqr.base-url=https://img.vietqr.io/image
mbbank.vietqr.bin=970422
mbbank.vietqr.template=compact2
#tinh phi ship
ghn.api.base-url=https://online-gateway.ghn.vn/shiip/public-api
ghn.token=368ca902-310f-11f1-a5fa-7ec58214c74b
ghn.shop-id=6367622
ghn.from-district-id=1582
ghn.service-type-id=2
ghn.default-weight=1000
ghn.default-length=20
ghn.default-width=20
ghn.default-height=10